web/proto/urls.py
from django.urls import path
from .import views

app_name = 'proto'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('jaran/', views.jaran_search, name='jaran_search')
]

web/web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('proto.urls')),
]

web/proto/models.py
from django.db import models
from django.utils import timezone

class Prefecture(models.Model):
    name = models.CharField('都道府県名', max_length=10)
    def __str__(self):
        return self.name


class Spot(models.Model):
    name = models.CharField('観光地名', max_length=30)
    prefecture = models.ForeignKey(
        Prefecture, verbose_name='都道府県', on_delete=models.PROTECT
    )
    description = models.TextField('説明', default='')

    def __str__(self):
        return self.name

web/proto/forms.py
from django import forms
from .models import Prefecture, Spot

class SpotSearchForm(forms.Form):
    prefecture = forms.ModelChoiceField(
        queryset=Prefecture.objects, label='都道府県', required=False
    )

class JaranSearchForm(forms.Form):
    pref_choices = [('東京都','東京都'), ('大阪府','大阪府')]
    prefecture = forms.ChoiceField(label='都道府県', choices=pref_choices, required=True)

web/proto/views.py
from django.views import generic
from django.shortcuts import render
from .models import Spot
from .forms import SpotSearchForm, JaranSearchForm
import requests
from bs4 import BeautifulSoup

api_key = "psc16cc2723f3d"
pref_code = {'北海道': '010000','青森県': '020000','岩手県': '030000','宮城県': '040000','秋田県': '050000','山形県': '060000',
            '福島県': '070000','栃木県': '080000','群馬県': '090000','茨城県': '100000','埼玉県': '110000','千葉県': '120000',
            '東京都': '130000','神奈川県': '140000','山梨県': '150000','長野県': '160000','新潟県': '170000','富山県': '180000',
            '石川県': '190000','福井県': '200000','静岡県': '210000','岐阜県': '220000','愛知県': '230000','三重県': '240000',
            '滋賀県': '250000','京都府': '260000','大阪府': '270000','兵庫県': '280000','奈良県': '290000','和歌山県': '300000',
            '鳥取県': '310000','島根県': '320000','岡山県': '330000','広島県': '340000','山口県': '350000','徳島県': '360000',
            '香川県': '370000','愛媛県': '380000','高知県': '390000','福岡県': '400000','佐賀県': '410000','長崎県': '420000',
            '熊本県': '430000','大分県': '440000','宮崎県': '450000','鹿児島県': '460000','沖縄県': '470000'}

class IndexView(generic.TemplateView):
    template_name = 'proto/proto_list.html'

class SearchView(generic.ListView):
    model = Spot

    def get_context_data(self):
        """テンプレートへ渡す辞書の作成"""
        context = super().get_context_data()
        context['form'] = SpotSearchForm(self.request.GET)
        return context

    def get_queryset(self):
        """テンプレートへ渡す「prefecture_list」を作成する"""
        form = SpotSearchForm(self.request.GET)
        form.is_valid()

        queryset = super().get_queryset()

        # 都道府県の選択があれば、絞り込み(filter)
        prefecture = form.cleaned_data['prefecture']
        if prefecture:
            queryset = queryset.filter(prefecture=prefecture)

        return queryset

def jaran_search(request):
    form = JaranSearchForm(request.GET or None)
    form.is_valid()
    context = {'form':form}
    if request.method == 'POST':
        data = request.POST
        pref = data['prefecture']
        code = pref_code[pref]
        res = get_api_response(code)
        context['prefecture'] = pref
        context['hotelinfo_list'] = res
    return render(request, 'proto/jaran_search.html',context)

# 指定した都道府県のホテル検索結果を取得
def get_api_response(code):
    url = 'http://jws.jalan.net/APILite/HotelSearch/V1/?key={0}&pref={1}'.format(api_key, code)
    print(url)
    response = requests.get(url)
    response.encoding = response.apparent_encoding
    bs = BeautifulSoup(response.text, 'xml')
    hotel_list = []
    for hotel in bs.find_all('Hotel'):
        name = hotel.HotelName.string
        address = hotel.HotelAddress.string
        hotel_list.append((name,address))
    return hotel_list

web/proto/templates/proto/base.html
<!doctype html>
<html lang="ja">
  <head>
    <title>プロトタイプ</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>
  {% block extracss %}{% endblock %}
  <body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
      

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block extrajs %}{% endblock %}
  </body>
</html>

web/proto/templates/proto/jaran_search.html
{% extends "proto/base.html" %}

{% block content %}
  {{ message }}
  <hr>
  <form method="POST" action="">
    {{form.prefecture.label}}{{form.prefecture}}
    <input type="submit" value="送信">
    {% csrf_token %}
  </form>

<table class="table table-hover">
  <thead>
    <tr>
      <th>ホテル名</th>
      <th>住所</th>
    </tr>
  </thead>
  <tbody>
    {% for hotelinfo in hotelinfo_list %}
    <tr>
      <th scope="row"> {{ forloop.counter }}</th>
      <th> {{ hotelinfo.0 }} </th>
      <th> {{ hotelinfo.1 }} </th>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

web/proto/templates/proto/proto_list.html
{%extends 'proto/base.html'%}

{% block content%}
トップページだよ
<div>
  <a href = "{% url 'proto:search' %}"> 観光地検索画面へ </a> <br>
  <a href = "{% url 'admin:index' %}">　管理画面へ </a> <br>
  <a href = "{% url 'proto:jaran_search' %}"> じゃらんホテル検索へ </a>
</div>
{% endblock %}

web/proto/templates/proto/spot_list.html
{% extends 'proto/base.html' %}

{% block content %}
<form action="" method="GET">
{{ form }}
<button type="submit">検索</button>
</form>

<table class="table table-bordered mt-4">
  <thead>
    <tr>
      <th>ID</th>
      <th>名前</th>
      <th>都道府県名</th>
      <th>説明</th>
    </tr>
  </thead>
  <tbody>
    {% for spot in spot_list %}
    <tr>
      <td>{{ spot.pk }}</td>
      <td>{{ spot.name }}</td>
      <td>{{ spot.prefecture }}</td>
      <td>{{ spot.description }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}